version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    expose:
      - "15672"
      - "5672"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
